version: '3.8'

services:
  # Backend service
  genai-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genai-chat-backend
    ports:
      - "5000:5000"
    environment:
      # Users will provide this at runtime
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service (simple HTTP server)
  genai-frontend:
    image: nginx:alpine
    container_name: genai-chat-frontend
    ports:
      - "3000:80"
    volumes:
      - ./react_frontend.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - genai-backend
    restart: unless-stopped

networks:
  default:
    name: genai-chat-network